# Generated by Django 5.2.16 on 2026-07-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="enrollment",
        ),
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
